"""Add TenantProfile model with user relationship

Revision ID: ea45ddbf895d
Revises: 31a59fdd3d54
Create Date: 2025-09-14 05:36:21.347940

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'ea45ddbf895d'
down_revision = '31a59fdd3d54'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create tenant_profiles table
    op.create_table('tenant_profiles',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('contact_email', sa.String(length=255), nullable=False),
        sa.Column('contact_phone', sa.String(length=20), nullable=False),
        sa.Column('address', sa.String(length=500), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', name='uq_tenant_profile_user_id')
    )
    
    # Create indexes
    op.create_index(op.f('ix_tenant_profiles_id'), 'tenant_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_tenant_profiles_user_id'), 'tenant_profiles', ['user_id'], unique=True)
    op.create_index(op.f('ix_tenant_profiles_contact_email'), 'tenant_profiles', ['contact_email'], unique=False)
    op.create_index(op.f('ix_tenant_profiles_contact_phone'), 'tenant_profiles', ['contact_phone'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes
    op.drop_index(op.f('ix_tenant_profiles_contact_phone'), table_name='tenant_profiles')
    op.drop_index(op.f('ix_tenant_profiles_contact_email'), table_name='tenant_profiles')
    op.drop_index(op.f('ix_tenant_profiles_user_id'), table_name='tenant_profiles')
    op.drop_index(op.f('ix_tenant_profiles_id'), table_name='tenant_profiles')
    
    # Drop table
    op.drop_table('tenant_profiles')
    
    # ### end Alembic commands ###
