"""Add a new column UserStatus

Revision ID: eadd04e62bf3
Revises: ea45ddbf895d
Create Date: 2025-09-22 09:26:36.011938

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "eadd04e62bf3"
down_revision = "ea45ddbf895d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column(
        "users",
        sa.Column(
            "status",
            postgresql.ENUM(
                "NEW",
                "ACTIVE",
                "INACTIVE",
                "DELETED",
                "WAITING_FOR_ADMIN_APPROVAL",
                "WAITING_FOR_TENANT_APPROVAL",
                "REJECTED",
                name="userstatus",
            ),
            default="NEW",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "status")
    op.drop_column("users", "deleted_at")
    # ### end Alembic commands ###
