from enum import Enum


class LimitType(Enum):
    # Usage limits
    TOTAL_USAGE = "TOTAL_USAGE"
    USAGE_PER_USER = "USAGE_PER_USER"
    USAGE_PER_STORE = "USAGE_PER_STORE"
    USAGE_PER_TENANT = "USAGE_PER_TENANT"

    # Amount limits
    TOTAL_AMOUNT = "TOTAL_AMOUNT"
    AMOUNT_PER_USER = "AMOUNT_PER_USER"
    AMOUNT_PER_STORE = "AMOUNT_PER_STORE"
    AMOUNT_PER_TENANT = "AMOUNT_PER_TENANT"
