from enum import Enum


class Operator(Enum):
    EQUAL = "EQUAL"
    NOT_EQUAL = "NOT_EQUAL"

    GREATER_THAN = "GREATER_THAN"
    LESS_THAN = "LESS_THAN"

    GREATER_THAN_OR_EQUAL = "GREATER_THAN_OR_EQUAL"
    LESS_THAN_OR_EQUAL = "LESS_THAN_OR_EQUAL"

    CONTAINS = "CONTAINS"
    NOT_CONTAINS = "NOT_CONTAINS"

    IN = "IN"
    NOT_IN = "NOT_IN"

    BETWEEN = "BETWEEN"
    NOT_BETWEEN = "NOT_BETWEEN"
